// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA12xiEGGUW2Z_n46FVAu3mm2N13cGbXjU',
    appId: '1:645140837596:android:2af3a2470296f958f9b019',
    messagingSenderId: '645140837596',
    projectId: 'leasing-f3da0',
    storageBucket: 'leasing-f3da0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOmyR9WkLo87b_FbpnD1-em7jIGr3Yz84',
    appId: '1:645140837596:ios:a008b1563fd534a2f9b019',
    messagingSenderId: '645140837596',
    projectId: 'leasing-f3da0',
    storageBucket: 'leasing-f3da0.appspot.com',
    iosBundleId: 'com.example.leasingCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxNSVYMI8reNWsEAIb8yYfRBWWCZTDqlw',
    appId: '1:645140837596:web:ea85c2aca83ca242f9b019',
    messagingSenderId: '645140837596',
    projectId: 'leasing-f3da0',
    authDomain: 'leasing-f3da0.firebaseapp.com',
    storageBucket: 'leasing-f3da0.appspot.com',
    measurementId: 'G-6J0TWN08T7',
  );
}
